export const categories = [
  { name: 'Action (set A)' },
  { name: 'Action (set B)' },
  { name: 'Animal (set A)' },
  { name: 'Animal (set B)' },
  { name: 'Clothes' },
  { name: 'Emotions' },
  { name: 'Movement' },
  { name: 'Adjective' },
];

export const cards = [
  {
    categoryName: 'Action (set A)',
    word: 'cry',
    translation: 'плакать',
    picture: 'img/cry.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/cry.mp3',
  },
  {
    categoryName: 'Action (set A)',
    word: 'dance',
    translation: 'танцевать',
    picture: 'img/dance.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/dance.mp3',
  },
  {
    categoryName: 'Action (set A)',
    word: 'dive',
    translation: 'нырять',
    picture: 'img/dive.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/dive.mp3',
  },
  {
    categoryName: 'Action (set A)',
    word: 'draw',
    translation: 'рисовать',
    picture: 'img/draw.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/draw.mp3',
  },
  {
    categoryName: 'Action (set A)',
    word: 'fish',
    translation: 'ловить рыбу',
    picture: 'img/fish.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/fish.mp3',
  },
  {
    categoryName: 'Action (set A)',
    word: 'fly',
    translation: 'летать',
    picture: 'img/fly.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/fly.mp3',
  },
  {
    categoryName: 'Action (set A)',
    word: 'hug',
    translation: 'обнимать',
    picture: 'img/hug.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/hug.mp3',
  },
  {
    categoryName: 'Action (set A)',
    word: 'jump',
    translation: 'прыгать',
    picture: 'img/jump.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/jump.mp3',
  },
  {
    categoryName: 'Action (set B)',
    word: 'open',
    translation: 'открывать',
    picture: 'img/open.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/open.mp3',
  },
  {
    categoryName: 'Action (set B)',
    word: 'play',
    translation: 'играть',
    picture: 'img/play.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/play.mp3',
  },
  {
    categoryName: 'Action (set B)',
    word: 'point',
    translation: 'указывать',
    picture: 'img/point.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/point.mp3',
  },
  {
    categoryName: 'Action (set B)',
    word: 'ride',
    translation: 'ездить',
    picture: 'img/ride.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/ride.mp3',
  },
  {
    categoryName: 'Action (set B)',
    word: 'run',
    translation: 'бегать',
    picture: 'img/run.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/run.mp3',
  },
  {
    categoryName: 'Action (set B)',
    word: 'sing',
    translation: 'петь',
    picture: 'img/sing.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/sing.mp3',
  },
  {
    categoryName: 'Action (set B)',
    word: 'skip',
    translation: 'пропускать, прыгать',
    picture: 'img/skip.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/skip.mp3',
  },
  {
    categoryName: 'Action (set B)',
    word: 'swim',
    translation: 'плавать',
    picture: 'img/swim.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/swim.mp3',
  },
  {
    categoryName: 'Animal (set A)',
    word: 'cat',
    translation: 'кот',
    picture: 'img/cat.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/cat.mp3',
  },
  {
    categoryName: 'Animal (set A)',
    word: 'chick',
    translation: 'цыплёнок',
    picture: 'img/chick.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/chick.mp3',
  },
  {
    categoryName: 'Animal (set A)',
    word: 'chicken',
    translation: 'курица',
    picture: 'img/chicken.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/chicken.mp3',
  },
  {
    categoryName: 'Animal (set A)',
    word: 'dog',
    translation: 'собака',
    picture: 'img/dog.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/dog.mp3',
  },
  {
    categoryName: 'Animal (set A)',
    word: 'horse',
    translation: 'лошадь',
    picture: 'img/horse.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/horse.mp3',
  },
  {
    categoryName: 'Animal (set A)',
    word: 'pig',
    translation: 'свинья',
    picture: 'img/pig.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/pig.mp3',
  },
  {
    categoryName: 'Animal (set A)',
    word: 'rabbit',
    translation: 'кролик',
    picture: 'img/rabbit.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/rabbit.mp3',
  },
  {
    categoryName: 'Animal (set A)',
    word: 'sheep',
    translation: 'овца',
    picture: 'img/sheep.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/sheep.mp3',
  },
  {
    categoryName: 'Animal (set B)',
    word: 'bird',
    translation: 'птица',
    picture: 'img/bird.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/bird.mp3',
  },
  {
    categoryName: 'Animal (set B)',
    word: 'fish',
    translation: 'рыба',
    picture: 'img/fish1.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/fish.mp3',
  },
  {
    categoryName: 'Animal (set B)',
    word: 'frog',
    translation: 'жаба',
    picture: 'img/frog.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/frog.mp3',
  },
  {
    categoryName: 'Animal (set B)',
    word: 'giraffe',
    translation: 'жирафа',
    picture: 'img/giraffe.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/giraffe.mp3',
  },
  {
    categoryName: 'Animal (set B)',
    word: 'lion',
    translation: 'лев',
    picture: 'img/lion.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/lion.mp3',
  },
  {
    categoryName: 'Animal (set B)',
    word: 'mouse',
    translation: 'мышь',
    picture: 'img/mouse.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/mouse.mp3',
  },
  {
    categoryName: 'Animal (set B)',
    word: 'turtle',
    translation: 'черепаха',
    picture: 'img/turtle.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/turtle.mp3',
  },
  {
    categoryName: 'Animal (set B)',
    word: 'dolphin',
    translation: 'дельфин',
    picture: 'img/dolphin.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/dolphin.mp3',
  },
  {
    categoryName: 'Clothes',
    word: 'skirt',
    translation: 'юбка',
    picture: 'img/skirt.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/skirt.mp3',
  },
  {
    categoryName: 'Clothes',
    word: 'pants',
    translation: 'брюки',
    picture: 'img/pants.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/pants.mp3',
  },
  {
    categoryName: 'Clothes',
    word: 'blouse',
    translation: 'блузка',
    picture: 'img/blouse.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/blouse.mp3',
  },
  {
    categoryName: 'Clothes',
    word: 'dress',
    translation: 'платье',
    picture: 'img/dress.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/dress.mp3',
  },
  {
    categoryName: 'Clothes',
    word: 'boot',
    translation: 'ботинок',
    picture: 'img/boot.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/boot.mp3',
  },
  {
    categoryName: 'Clothes',
    word: 'shirt',
    translation: 'рубашка',
    picture: 'img/shirt.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/shirt.mp3',
  },
  {
    categoryName: 'Clothes',
    word: 'coat',
    translation: 'пальто',
    picture: 'img/coat.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/coat.mp3',
  },
  {
    categoryName: 'Clothes',
    word: 'shoe',
    translation: 'туфли',
    picture: 'img/shoe.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/shoe.mp3',
  },
  {
    categoryName: 'Emotions',
    word: 'sad',
    translation: 'грустный',
    picture: 'img/sad.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/sad.mp3',
  },
  {
    categoryName: 'Emotions',
    word: 'angry',
    translation: 'сердитый',
    picture: 'img/angry.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/angry.mp3',
  },
  {
    categoryName: 'Emotions',
    word: 'happy',
    translation: 'счастливый',
    picture: 'img/happy.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/happy.mp3',
  },
  {
    categoryName: 'Emotions',
    word: 'tired',
    translation: 'уставший',
    picture: 'img/tired.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/tired.mp3',
  },
  {
    categoryName: 'Emotions',
    word: 'surprised',
    translation: 'удивлённый',
    picture: 'img/surprised.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/surprised.mp3',
  },
  {
    categoryName: 'Emotions',
    word: 'scared',
    translation: 'испуганный',
    picture: 'img/scared.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/scared.mp3',
  },
  {
    categoryName: 'Emotions',
    word: 'smile',
    translation: 'улыбка',
    picture: 'img/smile.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/smile.mp3',
  },
  {
    categoryName: 'Emotions',
    word: 'laugh',
    translation: 'смех',
    picture: 'img/laugh.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/laugh.mp3',
  },
  {
    categoryName: 'Movement',
    word: 'bend',
    translation: 'наклоняться',
    picture: 'img/bend.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/bend.mp3',
  },
  {
    categoryName: 'Movement',
    word: 'climb',
    translation: 'взбираться',
    picture: 'img/climb.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/climb.mp3',
  },
  {
    categoryName: 'Movement',
    word: 'crawl',
    translation: 'ползти',
    picture: 'img/crawl.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/crawl.mp3',
  },
  {
    categoryName: 'Movement',
    word: 'fall',
    translation: 'падать',
    picture: 'img/fall.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/fall.mp3',
  },
  {
    categoryName: 'Movement',
    word: 'get-up',
    translation: 'вставать',
    picture: 'img/get-up.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/get-up.mp3',
  },
  {
    categoryName: 'Movement',
    word: 'go down',
    translation: 'спускаться',
    picture: 'img/go-down.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/go-down.mp3',
  },
  {
    categoryName: 'Movement',
    word: 'kick',
    translation: 'пинать',
    picture: 'img/kick.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/kick.mp3',
  },
  {
    categoryName: 'Movement',
    word: 'throw',
    translation: 'бросать',
    picture: 'img/throw.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/throw.mp3',
  },
  {
    categoryName: 'Adjective',
    word: 'big',
    translation: 'большой',
    picture: 'img/big.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/big.mp3',
  },
  {
    categoryName: 'Adjective',
    word: 'fast',
    translation: 'быстрый',
    picture: 'img/fast.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/fast.mp3',
  },
  {
    categoryName: 'Adjective',
    word: 'friendly',
    translation: 'дружелюбный',
    picture: 'img/friendly.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/friendly.mp3',
  },
  {
    categoryName: 'Adjective',
    word: 'old',
    translation: 'старый',
    picture: 'img/old.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/old.mp3',
  },
  {
    categoryName: 'Adjective',
    word: 'slow',
    translation: 'медленный',
    picture: 'img/slow.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/slow.mp3',
  },
  {
    categoryName: 'Adjective',
    word: 'small',
    translation: 'маленький',
    picture: 'img/small.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/small.mp3',
  },
  {
    categoryName: 'Adjective',
    word: 'unfriendly',
    translation: 'недружелюбный',
    picture: 'img/unfriendly.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/unfriendly.mp3',
  },
  {
    categoryName: 'Adjective',
    word: 'young',
    translation: 'молодой',
    picture: 'img/young.jpg',
    audioSrc: 'https://wooordhunt.ru/data/sound/sow/us/young.mp3',
  }
];